export  const  baseRoute= "http://127.0.0.1:8000/";
export const baseImgRoute = "http://127.0.0.1:8000"
export const authRoute =baseRoute+"register/";
export const loginRoute = baseRoute+"login/";
export const addStudentRoute =baseRoute+"student/add/";
export const studentsRoute = baseRoute+"students/";
export const  studentDetailRoute = baseRoute+"student/"
export const attendanceRoute = baseRoute+"student/attendance/";
export const attendanceUpdateRoute =baseRoute+"attendance/update/";